Schema export: export bare types as non-nullable
burner/graphqld pull request #58
Opened 2021-01-07 01:25 UTC by moon-chilled

Aside: does it make sense to have both `GQLDNullable` and `GQLDNonNullable`?  Would it make more sense for one of them be removed?

2021-01-09 00:09 UTC, moon-chilled commented
Or maybe another option: make nullability be a flag on existing types.

2021-01-11 16:36 UTC, burner commented
I'll find tomorrow for this. Sorry for the delay

2021-01-12 07:45 UTC, burner requested changes
Could you please a a Nullable!(bare type) test just to make sure that is handled correctly.

I did see that in the diff.

2021-01-12 07:45 UTC, burner commented on source/graphql/schema/toschemafile.d
> +string gqldTypeToString(const(GQLDType) t, string nameSuffix = "", bool nonNullable = true) {
could you please turn the bool into a std.typecons.Flag!"NonNullable" passing boolean around is not nice.

I properly do it somewhere as well but, consider this a "do as I say, not as I do" situtation.

2021-01-15 05:24 UTC, moon-chilled commented
@burner ping

2021-01-26 13:49 UTC, merged

2021-01-26 13:50 UTC, burner commented
sorry for taking so long